// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6h65ekGhKtHooWowOkCTpfYlwxxJ5rrE',
    appId: '1:9130045207:web:ba814428f5c06de1961152',
    messagingSenderId: '9130045207',
    projectId: 'lab09-755af',
    authDomain: 'lab09-755af.firebaseapp.com',
    storageBucket: 'lab09-755af.appspot.com',
    measurementId: 'G-46T7479J3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADgER0p4e-6yhnBK9ry-lv89XY6RY53Do',
    appId: '1:9130045207:android:be8382df59aac7c2961152',
    messagingSenderId: '9130045207',
    projectId: 'lab09-755af',
    storageBucket: 'lab09-755af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXJYtMIJGeuq3Pj0SupdZ4tCTF-30hnAU',
    appId: '1:9130045207:ios:0663c703e57936d3961152',
    messagingSenderId: '9130045207',
    projectId: 'lab09-755af',
    storageBucket: 'lab09-755af.appspot.com',
    iosBundleId: 'com.example.lab09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXJYtMIJGeuq3Pj0SupdZ4tCTF-30hnAU',
    appId: '1:9130045207:ios:195db2e582f4f48f961152',
    messagingSenderId: '9130045207',
    projectId: 'lab09-755af',
    storageBucket: 'lab09-755af.appspot.com',
    iosBundleId: 'com.example.lab09.RunnerTests',
  );
}
